lumi_text:
  text: "26.6717 fb^{-1} (13.6 TeV)"
  pos_ref: inner_right_top
  pos: [ 0, -0.03 ]
  text_size: 0.035
  font: 42
  align: right_bottom

channel_text:
  'eTau': 'bb#tau_{e}#tau_{h}'
  'muTau': 'bb#tau_{#mu}#tau_{h}'
  'tauTau': 'bb#tau_{h}#tau_{h}'
  'muMu': 'bb#tau_{#mu}#tau_{#mu}'
  'eMu': 'bb#tau_{e}#tau_{#mu}'
  'eE': 'bb#tau_{e}#tau_{e}'

