tau1_pt:
  x_bins: [0, 40, 60, 80, 100, 150, 200, 250, 300]
  x_title: tau_1 p_{T} (GeV)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False

tautau_m_vis:
  x_bins: [0, 40, 60, 80, 100, 120, 140, 160,180, 200, 250, 300, 350, 400, 450, 500, 1000]
  x_title: M^{\tau\tau}_{vis} (GeV
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: True

bbtautau_mass:
  x_bins: "50|150:1500"
  x_title: "M^{HH}_{vis} (GeV)"
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: True

dR_tautau:
  x_bins: "10|0:5"
  x_title: \Delta R(\tau\tau)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: True