
- name: DY
  title: "DY #rightarrow ll + jets"
  color: kAzure+10
- name: TT
  title: t#bar{t}
  color: kGreen-3
- name: W
  title: "W #rightarrow l#nu + jets"
  color: kYellow-7
#- name: HHnonRes
  #title: "HH SM"
  #color: kPink+1
- name: GluGluToBulkGraviton_1250
  title: "GluGluBulkGraviton - 1250 GeV"
  type: signal
  color: kGreen
  #scale: 0.05
- name: GluGluToRadion_1250
  title: "GluGluRadion - 1250"
  type: signal
  color: kCyan
- name: GluGluToRadion_700
  title: "GluGluRadion - 700 GeV"
  type: signal
  color: kBlue
- name: GluGluToRadion_450
  title: "GluGluRadion - 450 GeV"
  type: signal
  color: kViolet

  #scale: 0.05
#- name: VBFToBulkGraviton
#  title: "qqHH #rightarrow bb#tau#tau BulkGraviton"
#  type: signal
#  color: kMagenta
#  scale: 5
#- name: VBFToRadion
#  title: "qqHH #rightarrow bb#tau#tau Radion"
#  type: signal
#  color: kViolet+4
#  scale: 5
- name: Other
  title: "other backgrounds"
  color: kRed-4
- name: QCD
  title: QCD
  color: kPink+1
- name: data
  title: "data obs"
  type: data