common:
    exclude_columns:
        - Jet_btagDeepCvB
        - Jet_btagDeepCvL
        - Jet_qgl
        - Jet_neEmEF
        - Jet_neHEF
        - Jet_chFPV0EF
        - Jet_chFPV1EF
        - Jet_chFPV2EF
        - Jet_chFPV3EF
        - Jet_chHEF
        - Jet_hfsigmaEtaEta
        - Jet_hfsigmaPhiPhi
        - Jet_chEmEF
        - Jet_muEF
        - Jet_hfcentralEtaStripSize
        - Jet_hfadjacentEtaStripsSize
        - Jet_nMuons
        - Jet_muonIdx1
        - Jet_muonIdx2
        - Jet_nElectrons
        - Jet_electronIdx1
        - Jet_electronIdx2
        - Electron_miniPFRelIso_all
        - Electron_miniPFRelIso_chg
        - Electron_eInvMinusPInv
        - Electron_deltaEtaSC
        - Electron_ip3d
        - Electron_sip3d
        - Electron_mvaTTH
        - Electron_sieie
        - Electron_scEtOverPt
        - Electron_jetRelIso
        - Electron_r9
        - Electron_jetPtRelv2
        - Electron_vidNestedWPBitmap
        - Electron_energyErr
        - Electron_hoe
        - Electron_vidNestedWPBitmapHEEP
        - Electron_dzErr
        - Electron_dxyErr
        - Electron_dr03EcalRecHitSumEt
        - Electron_dr03HcalDepth1TowerSumEt
        - Electron_jetNDauCharged
        - Electron_dr03TkSumPt
        - Electron_dr03TkSumPtHEEP
        - Electron_tightCharge
        - Electron_isPFcand
        - Electron_lostHits
        - Electron_cutBased_HEEP
        - Electron_seedGain
        - Electron_photonIdx
        - ^Electron_mvaFall17V1.*$
        - Muon_miniPFRelIso_all
        - Muon_miniPFRelIso_chg
        - Muon_dxybs
        - Muon_ip3d
        - Muon_sip3d
        - Muon_mvaTTH
        - Muon_segmentComp
        - Muon_jetRelIso
        - Muon_jetPtRelv2
        - Muon_tkRelIso
        - Muon_dzErr
        - Muon_dxyErr
        - Muon_nTrackerLayers
        - Muon_nStations
        - Muon_jetNDauCharged
        - Muon_fsrPhotonIdx
        - Tau_idAntiEle
        - Tau_idAntiEle2018
        - Tau_idAntiEleDeadECal
        - Tau_idMVAnewDM2017v2
        - Tau_idMVAoldDM
        - Tau_idMVAoldDM2017v1
        - Tau_idMVAoldDM2017v2
        - Tau_idMVAoldDMdR032017v2
        - Tau_leadTkDeltaEta
        - Tau_leadTkDeltaPhi
        - Tau_leadTkPtOverTauPt
        - Tau_photonsOutsideSignalCone
        - Tau_puCorr
        - Tau_rawAntiEle
        - Tau_rawAntiEle2018
        - Tau_rawAntiEleCat
        - Tau_rawAntiEleCat2018
        - Tau_chargedIso
        - Tau_neutralIso
        - Tau_rawMVAnewDM2017v2
        - Tau_rawMVAoldDM
        - Tau_rawMVAoldDM2017v1
        - Tau_rawMVAoldDM2017v2
        - Tau_rawMVAoldDMdR032017v2
        - ^(n|)SV(_.*|)$
        - ^(n|)Photon(_.*|)$
        - ^(n|)LowPtElectron(_.*|)$
        - ^(n|)SoftActivityJet(.*|)$
        - ^(n|)IsoTrack(_.*|)$
        - ^HTXS_.*$
        - ^(n|)FsrPhoton(_.*|)$
        - ^(n|)GenDressedLepton(_.*|)$
        - ^(n|)GenIsolatedPhoton(_.*|)$
signal:
    sampleTypes:
        - GluGluToRadion
