############## Signals ##############
GluGlutoRadiontoHHto2B2Tau_M-250:
  sampleType: GluGluToRadion
  mass: 250
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-260:
  sampleType: GluGluToRadion
  mass: 260
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-270:
  sampleType: GluGluToRadion
  mass: 270
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-280:
  sampleType: GluGluToRadion
  mass: 280
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-300:
  sampleType: GluGluToRadion
  mass: 300
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-350:
  sampleType: GluGluToRadion
  mass: 350
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-450:
  sampleType: GluGluToRadion
  mass: 450
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-550:
  sampleType: GluGluToRadion
  mass: 550
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-600:
  sampleType: GluGluToRadion
  mass: 600
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-650:
  sampleType: GluGluToRadion
  mass: 650
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-700:
  sampleType: GluGluToRadion
  mass: 700
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-800:
  sampleType: GluGluToRadion
  mass: 800
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-1000:
  sampleType: GluGluToRadion
  mass: 1000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-1200:
  sampleType: GluGluToRadion
  mass: 1200
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-1400:
  sampleType: GluGluToRadion
  mass: 1400
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-1600:
  sampleType: GluGluToRadion
  mass: 1600
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-1800:
  sampleType: GluGluToRadion
  mass: 1800
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-2000:
  sampleType: GluGluToRadion
  mass: 2000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-2500:
  sampleType: GluGluToRadion
  mass: 2500
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-3000:
  sampleType: GluGluToRadion
  mass: 3000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-4000:
  sampleType: GluGluToRadion
  mass: 4000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M-5000:
  sampleType: GluGluToRadion
  mass: 5000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-250:
  sampleType: GluGluToBulkGraviton
  mass: 250
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-260:
  sampleType: GluGluToBulkGraviton
  mass: 260
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-270:
  sampleType: GluGluToBulkGraviton
  mass: 270
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-280:
  sampleType: GluGluToBulkGraviton
  mass: 280
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-300:
  sampleType: GluGluToBulkGraviton
  mass: 300
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-350:
  sampleType: GluGluToBulkGraviton
  mass: 350
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-450:
  sampleType: GluGluToBulkGraviton
  mass: 450
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-550:
  sampleType: GluGluToBulkGraviton
  mass: 550
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-600:
  sampleType: GluGluToBulkGraviton
  mass: 600
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-650:
  sampleType: GluGluToBulkGraviton
  mass: 650
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-700:
  sampleType: GluGluToBulkGraviton
  mass: 700
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-800:
  sampleType: GluGluToBulkGraviton
  mass: 800
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-1000:
  sampleType: GluGluToBulkGraviton
  mass: 1000
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-1200:
  sampleType: GluGluToBulkGraviton
  mass: 1200
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-1400:
  sampleType: GluGluToBulkGraviton
  mass: 1400
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-1600:
  sampleType: GluGluToBulkGraviton
  mass: 1600
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-1800:
  sampleType: GluGluToBulkGraviton
  mass: 1800
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-2000:
  sampleType: GluGluToBulkGraviton
  mass: 2000
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-2500:
  sampleType: GluGluToBulkGraviton
  mass: 2500
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-3000:
  sampleType: GluGluToBulkGraviton
  mass: 3000
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-4000:
  sampleType: GluGluToBulkGraviton
  mass: 4000
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M-5000:
  sampleType: GluGluToBulkGraviton
  mass: 5000
  spin: 2
  generator: madgraph
  crossSection: 1pb
####################Non-resonant signals###########
GluGlutoHHto2B2Tau_kl-0p00_kt-1p00_c2-0p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl-0p00_kt-1p00_c2-1p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-0p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-0p10:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-0p35:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-3p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl-1p00_kt-1p00_c2-m2p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl-2p45_kt-1p00_c2-0p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl-5p00_kt-1p00_c2-0p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-1_C2V-1_C3-1:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-1_C2V-1_C3-2:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-1_C2V-2_C3-1:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-1p74_C2V-1p37_C3-14p4:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-m0p012_C2V-0p030_C3-10p2:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-m0p758_C2V-1p44_C3-m19p3:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-m0p962_C2V-0p959_C3-m1p43:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-m1p21_C2V-1p94_C3-m0p94:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-m1p60_C2V-2p72_C3-m1p36:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV-m2p12_C2V-3p87_C3-m5p96:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_1_C2V_0_C3_1:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_1_C2V_1_C3_1:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb