GLOBAL:
  sampleSelection:
    - drop ^.*
    - keep ^TT.*
    - keep ^ttH.*
    - keep ^ST.*
    - keep DYto2L_M_10to50_amcatnloFXFX
    - keep DYto2L_M_50_amcatnloFXFX
    - keep WtoLNu_amcatnloFXFX
    - keep WW
    - keep WZ
    - keep ZZ
    - keep WWW_4F
    - keep WWZ_4F
    - keep WZZ
    - keep ZZZ
    - keep ^Muon_.*
    - keep ^SingleMuon_.*
    - keep ^DoubleMuon_.*
    - keep ^Tau_.*
    - keep ^EGamma_.*
    - keep ^MuonEG_.*
    - keep ^Jet.*
    - keep ^MET_.*
  use_stitching: false
  triggerFile: config/HH_bbtautau/Run3_2022/triggers.yaml
############## Signals ##############
GluGlutoRadiontoHHto2B2Tau_M_250:
  sampleType: GluGluToRadion
  mass: 250
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_260:
  sampleType: GluGluToRadion
  mass: 260
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_270:
  sampleType: GluGluToRadion
  mass: 270
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_280:
  sampleType: GluGluToRadion
  mass: 280
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_300:
  sampleType: GluGluToRadion
  mass: 300
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_350:
  sampleType: GluGluToRadion
  mass: 350
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_450:
  sampleType: GluGluToRadion
  mass: 450
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_550:
  sampleType: GluGluToRadion
  mass: 550
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_600:
  sampleType: GluGluToRadion
  mass: 600
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_650:
  sampleType: GluGluToRadion
  mass: 650
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_700:
  sampleType: GluGluToRadion
  mass: 700
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_800:
  sampleType: GluGluToRadion
  mass: 800
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_1000:
  sampleType: GluGluToRadion
  mass: 1000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_1200:
  sampleType: GluGluToRadion
  mass: 1200
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_1400:
  sampleType: GluGluToRadion
  mass: 1400
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_1600:
  sampleType: GluGluToRadion
  mass: 1600
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_1800:
  sampleType: GluGluToRadion
  mass: 1800
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_2000:
  sampleType: GluGluToRadion
  mass: 2000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_2500:
  sampleType: GluGluToRadion
  mass: 2500
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_3000:
  sampleType: GluGluToRadion
  mass: 3000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_4000:
  sampleType: GluGluToRadion
  mass: 4000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoRadiontoHHto2B2Tau_M_5000:
  sampleType: GluGluToRadion
  mass: 5000
  spin: 0
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_250:
  sampleType: GluGluToBulkGraviton
  mass: 250
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_260:
  sampleType: GluGluToBulkGraviton
  mass: 260
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_270:
  sampleType: GluGluToBulkGraviton
  mass: 270
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_280:
  sampleType: GluGluToBulkGraviton
  mass: 280
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_300:
  sampleType: GluGluToBulkGraviton
  mass: 300
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_350:
  sampleType: GluGluToBulkGraviton
  mass: 350
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_450:
  sampleType: GluGluToBulkGraviton
  mass: 450
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_550:
  sampleType: GluGluToBulkGraviton
  mass: 550
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_600:
  sampleType: GluGluToBulkGraviton
  mass: 600
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_650:
  sampleType: GluGluToBulkGraviton
  mass: 650
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_700:
  sampleType: GluGluToBulkGraviton
  mass: 700
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_800:
  sampleType: GluGluToBulkGraviton
  mass: 800
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_1000:
  sampleType: GluGluToBulkGraviton
  mass: 1000
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_1200:
  sampleType: GluGluToBulkGraviton
  mass: 1200
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_1400:
  sampleType: GluGluToBulkGraviton
  mass: 1400
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_1600:
  sampleType: GluGluToBulkGraviton
  mass: 1600
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_1800:
  sampleType: GluGluToBulkGraviton
  mass: 1800
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_2000:
  sampleType: GluGluToBulkGraviton
  mass: 2000
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_2500:
  sampleType: GluGluToBulkGraviton
  mass: 2500
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_3000:
  sampleType: GluGluToBulkGraviton
  mass: 3000
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_4000:
  sampleType: GluGluToBulkGraviton
  mass: 4000
  spin: 2
  generator: madgraph
  crossSection: 1pb
GluGlutoBulkGravitontoHHto2B2Tau_M_5000:
  sampleType: GluGluToBulkGraviton
  mass: 5000
  spin: 2
  generator: madgraph
  crossSection: 1pb
####################Non-resonant signals###########
GluGlutoHHto2B2Tau_kl_0p00_kt_1p00_c2_0p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_0p00_kt_1p00_c2_1p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p00_LHEweights:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p10:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p35:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_3p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_m2p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_2p45_kt_1p00_c2_0p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_2p45_kt_1p00_c2_0p00_LHEweights:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
GluGlutoHHto2B2Tau_kl_5p00_kt_1p00_c2_0p00:
  sampleType: HHnonRes
  generator: powheg
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_1_C2V_0_C3_1:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_1_C2V_1_C3_1:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_1_C2V_1_C3_1_v2:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_1_C2V_1_C3_2:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_1_C2V_2_C3_1:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_1p74_C2V_1p37_C3_14p4:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_m0p012_C2V_0p030_C3_10p2:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_m0p758_C2V_1p44_C3_m19p3:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_m0p962_C2V_0p959_C3_m1p43:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_m1p21_C2V_1p94_C3_m0p94:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_m1p60_C2V_2p72_C3_m1p36:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_m1p83_C2V_3p57_C3_m3p39:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
VBFHHto2B2Tau_CV_m2p12_C2V_3p87_C3_m5p96:
  sampleType: HHnonRes
  generator: madgraph
  mass: 125
  spin: 0
  crossSection: 1pb
