name: Formatting Check

on:
  pull_request:
    types: [ "opened", "synchronize", "reopened", "labeled" ]
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-flaf@main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get changed files
        id: changed-files
        uses: actions/github-script@v6
        with:
          script: |
            const files = await github.paginate(github.rest.pulls.listFiles, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            console.log(`Total files changed: ${files.length}`);
            const changedFiles = files.map(file => file.filename);
            core.setOutput('files', changedFiles.join(' '));

      - name: Install black
        run: pip install black

      - name: Check Python formatting
        run: |
          echo "${{ steps.changed-files.outputs.files }}" | tr ' ' '\n' | grep '\.py$' | xargs -r black --check --diff

      - name: Install yamllint
        run: pip install yamllint

      - name: Check YAML formatting
        run: |
          if [ -f ".yamllint" ]; then
            yamllint_config=".yamllint"
          elif [ -f "FLAF/.yamllint" ]; then
            yamllint_config="FLAF/.yamllint"
          else
            echo "No yamllint configuration file found."
            exit 1
          fi
          echo "${{ steps.changed-files.outputs.files }}" | tr ' ' '\n' | grep -E '\.(yaml|yml|yamllint)$' | xargs -r yamllint -s -c ${yamllint_config}

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install clang-format

      - name: Check C++ formatting
        run: |
          if [ -f ".clang-format" ]; then
            clang_format_style=".clang-format"
          elif [ -f "FLAF/.clang-format" ]; then
            clang_format_style="FLAF/.clang-format"
          else
            echo "No clang-format configuration file found."
            exit 1
          fi
          echo "${{ steps.changed-files.outputs.files }}" | tr ' ' '\n' | grep -E '\.(cpp|h|hpp|cc)$' | xargs -r clang-format --dry-run --Werror --style "file:${clang_format_style}"
